federation_version: 2
subgraphs:
  iss_possition:
    routing_url: https://o3pyjy0hy1.execute-api.us-east-1.amazonaws.com/dev/iss_position
    schema:
      file: ../subgraphs/issLocation/issLocationSchema.graphql